import React, { useState, useEffect, useRef } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ScrollView,
  ActivityIndicator, Alert, Image, TextInput, Modal
} from 'react-native';
import {
  doc, getDoc, updateDoc, collection, query,
  where, onSnapshot, orderBy, setDoc, increment
} from 'firebase/firestore';
import { updatePassword, EmailAuthProvider, reauthenticateWithCredential } from 'firebase/auth';
import { db, auth } from '../firebaseConfig';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const STATUS_OPTIONS = [
  { key: 'in_office', label: 'In Office',     labelAr: 'في العيادة',   color: '#16a34a', dot: '#22c55e' },
  { key: 'brb',       label: 'Be Right Back', labelAr: 'عودة قريباً',  color: '#d97706', dot: '#f59e0b' },
  { key: 'away',      label: 'Away',           labelAr: 'غائب',         color: '#dc2626', dot: '#ef4444' },
  { key: 'vacation',  label: 'On Vacation',   labelAr: 'في إجازة',     color: '#2563eb', dot: '#3b82f6' },
];

const dateKey = (d) => d.toISOString().split('T')[0];
const displayDate = (key) => new Date(key).toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' });

const formatCountdown = (endDate) => {
  const diff = endDate - new Date();
  if (diff <= 0) return 'Expired';
  const days    = Math.floor(diff / 86400000);
  const hours   = Math.floor((diff % 86400000) / 3600000);
  const minutes = Math.floor((diff % 3600000) / 60000);
  const seconds = Math.floor((diff % 60000) / 1000);
  return `${days}d ${hours}h ${minutes}m ${seconds}s`;
};

const generateQueueHTML = (profile, reservations, dateStr) => `
<!DOCTYPE html><html><head><meta charset="UTF-8"/>
<style>
  body { font-family: Arial, sans-serif; color: #1a1a1a; padding: 40px; }
  .header { border-bottom: 2px solid #16a34a; padding-bottom: 20px; margin-bottom: 24px; display:flex; justify-content:space-between; }
  .clinic { font-size: 20px; font-weight: 700; color: #16a34a; }
  .sub { font-size: 13px; color: #555; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #f0fdf4; padding: 10px 12px; text-align: left; font-size: 12px; color: #16a34a; border-bottom: 1px solid #d1fae5; }
  td { padding: 11px 12px; font-size: 13px; border-bottom: 1px solid #f3f4f6; }
  .badge { display:inline-block; padding:2px 8px; border-radius:20px; font-size:11px; font-weight:600; }
  .confirmed { background:#d1fae5; color:#065f46; }
  .pending   { background:#fef3c7; color:#92400e; }
  .footer { margin-top:24px; font-size:11px; color:#9ca3af; text-align:center; }
</style></head><body>
<div class="header">
  <div>
    <div class="clinic">${profile?.cabinetName || 'Clinic'}</div>
    <div class="sub">Dr. ${profile?.fullName || ''} · ${profile?.specialty || ''}</div>
    <div class="sub">${profile?.phone || ''}</div>
  </div>
  <div style="text-align:right">
    <div class="sub">Queue for</div>
    <div style="font-size:15px;font-weight:700">${dateStr}</div>
  </div>
</div>
<table>
  <thead><tr><th>#</th><th>Name</th><th>Phone</th><th>Time</th><th>Status</th><th>Note</th></tr></thead>
  <tbody>
    ${reservations.map((r, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${r.patientName || '—'}</td>
        <td>${r.patientPhone || '—'}</td>
        <td>${r.time || '—'}</td>
        <td><span class="badge ${r.status || 'pending'}">${r.status || 'pending'}</span></td>
        <td>${r.note || '—'}</td>
      </tr>`).join('')}
  </tbody>
</table>
<div style="text-align:right;margin-top:16px;font-size:13px">Total: <strong>${reservations.length}</strong></div>
<div class="footer">Generated by Dawini · ${new Date().toLocaleString()}</div>
</body></html>`;

export default function DoctorDashboardScreen({ navigation }) {
  const uid = auth.currentUser.uid;

  const [profile, setProfile]               = useState(null);
  const [loading, setLoading]               = useState(true);
  const [status, setStatus]                 = useState('in_office');
  const [acceptMode, setAcceptMode]         = useState('manual');
  const [reservations, setReservations]     = useState([]);
  const [subscriptionEnd, setSubscriptionEnd] = useState(null);
  const [countdown, setCountdown]           = useState('');
  const [slots, setSlots]                   = useState({});
  const [editingSlotDate, setEditingSlotDate] = useState(null);
  const [newSlotValue, setNewSlotValue]     = useState('');
  const [selectedCalendarDay, setSelectedCalendarDay] = useState(null);
  const [menuVisible, setMenuVisible]       = useState(false);
  const [pinModalVisible, setPinModalVisible] = useState(false);
  const [pinInput, setPinInput]             = useState('');
  const [savedPin, setSavedPin]             = useState('');
  const [pinMode, setPinMode]               = useState('enter');
  const [assistantActive, setAssistantActive] = useState(false);
  const [pwModalVisible, setPwModalVisible] = useState(false);
  const [currentPw, setCurrentPw]           = useState('');
  const [newPw, setNewPw]                   = useState('');
  const [confirmPw, setConfirmPw]           = useState('');

  const countdownRef = useRef(null);

  const today = new Date();
  const todayKey = dateKey(today);
  const calendarDays = Array.from({ length: 14 }, (_, i) => {
    const d = new Date(today); d.setDate(d.getDate() + i); return dateKey(d);
  });

  useEffect(() => {
    const fetchProfile = async () => {
      try {
        const snap = await getDoc(doc(db, "users", uid));
        if (snap.exists()) {
          const d = snap.data();
          setProfile(d);
          setStatus(d.status || 'in_office');
          setAcceptMode(d.acceptMode || 'manual');
          setSavedPin(d.assistantPin || '');
          if (d.subscriptionEnd) {
            const end = d.subscriptionEnd.toDate ? d.subscriptionEnd.toDate() : new Date(d.subscriptionEnd);
            setSubscriptionEnd(end);
          }
        }
      } catch (e) { console.log(e); }
      finally { setLoading(false); }
    };
    fetchProfile();
  }, []);

  useEffect(() => {
    if (!subscriptionEnd) return;
    countdownRef.current = setInterval(() => setCountdown(formatCountdown(subscriptionEnd)), 1000);
    setCountdown(formatCountdown(subscriptionEnd));
    return () => clearInterval(countdownRef.current);
  }, [subscriptionEnd]);

  useEffect(() => {
    if (!profile) return;
    const fetchSlots = async () => {
      const result = {};
      for (const day of calendarDays) {
        try {
          const s = await getDoc(doc(db, "slots", `${uid}_${day}`));
          result[day] = s.exists() ? s.data() : { max: profile.maxSlots || 10, booked: 0 };
        } catch (e) {}
      }
      setSlots(result);
    };
    fetchSlots();
  }, [profile]);

  useEffect(() => {
    const q = query(collection(db, "reservations"), where("doctorId", "==", uid), orderBy("date", "asc"));
    return onSnapshot(q, snap => setReservations(snap.docs.map(d => ({ id: d.id, ...d.data() }))));
  }, []);

  const updateStatus = async (s) => {
    const prev = status; setStatus(s);
    try { await updateDoc(doc(db, "users", uid), { status: s }); }
    catch { Alert.alert("Error", "Could not update status."); setStatus(prev); }
  };

  const updateAcceptMode = async (m) => {
    setAcceptMode(m);
    try { await updateDoc(doc(db, "users", uid), { acceptMode: m }); }
    catch { Alert.alert("Error", "Could not update mode."); }
  };

  const saveSlot = async (day, val) => {
    const max = parseInt(val);
    if (!max || max < 1) { Alert.alert("Invalid", "Enter a valid number."); return; }
    try {
      await setDoc(doc(db, "slots", `${uid}_${day}`), { doctorId: uid, date: day, max, booked: slots[day]?.booked || 0 });
      setSlots(p => ({ ...p, [day]: { ...p[day], max } }));
      setEditingSlotDate(null);
    } catch { Alert.alert("Error", "Could not save."); }
  };

  const handleCancel = (item) => {
    Alert.alert("Cancel Booking", `Cancel ${item.patientName || 'patient'}'s booking?\n\nWhat happens to the freed slot?`, [
      { text: "Open for next patient", onPress: async () => {
        await updateDoc(doc(db, "reservations", item.id), { status: 'cancelled' });
        const day = item.date?.toDate ? dateKey(item.date.toDate()) : item.date;
        if (day) {
          try {
            await updateDoc(doc(db, "slots", `${uid}_${day}`), { booked: increment(-1) });
            setSlots(p => ({ ...p, [day]: { ...p[day], booked: Math.max(0, (p[day]?.booked || 1) - 1) } }));
          } catch {}
        }
      }},
      { text: "Close the slot", onPress: async () => {
        await updateDoc(doc(db, "reservations", item.id), { status: 'cancelled' });
      }},
      { text: "Go Back", style: "cancel" }
    ]);
  };

  const confirmRes = async (id) => {
    try { await updateDoc(doc(db, "reservations", id), { status: 'confirmed' }); }
    catch { Alert.alert("Error", "Could not confirm."); }
  };

  const exportPDF = async () => {
    try {
      const todayRes = reservations
        .filter(r => { const d = r.date?.toDate ? dateKey(r.date.toDate()) : r.date; return d === todayKey; })
        .sort((a, b) => (a.time || '').localeCompare(b.time || ''));
      const html = generateQueueHTML(profile, todayRes, displayDate(todayKey));
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: "Today's Queue" });
    } catch {
      Alert.alert("Missing packages", "Run: npx expo install expo-print expo-sharing");
    }
  };

  const handleAssistantBtn = () => {
    if (assistantActive) { setAssistantActive(false); return; }
    setPinMode(savedPin ? 'enter' : 'set');
    setPinInput('');
    setPinModalVisible(true);
  };

  const handlePinSubmit = async () => {
    if (pinMode === 'set') {
      if (pinInput.length < 4) { Alert.alert("Invalid", "PIN must be at least 4 digits."); return; }
      await updateDoc(doc(db, "users", uid), { assistantPin: pinInput });
      setSavedPin(pinInput);
      setAssistantActive(true);
      setPinModalVisible(false);
    } else {
      if (pinInput === savedPin) { setAssistantActive(true); setPinModalVisible(false); }
      else { Alert.alert("Wrong PIN", "Incorrect PIN."); setPinInput(''); }
    }
  };

  const handlePasswordChange = async () => {
    if (!currentPw || !newPw || !confirmPw) { Alert.alert("Missing", "Fill all fields."); return; }
    if (newPw !== confirmPw) { Alert.alert("Mismatch", "Passwords don't match."); return; }
    if (newPw.length < 6) { Alert.alert("Too Short", "Min 6 characters."); return; }
    try {
      const cred = EmailAuthProvider.credential(auth.currentUser.email, currentPw);
      await reauthenticateWithCredential(auth.currentUser, cred);
      await updatePassword(auth.currentUser, newPw);
      Alert.alert("Done", "Password updated.");
      setPwModalVisible(false);
      setCurrentPw(''); setNewPw(''); setConfirmPw('');
    } catch (e) {
      Alert.alert("Error", e.code === 'auth/wrong-password' ? "Current password is wrong." : e.message);
    }
  };

  const todayQueue = reservations
    .filter(r => { const d = r.date?.toDate ? dateKey(r.date.toDate()) : r.date; return d === todayKey && r.status !== 'cancelled'; })
    .sort((a, b) => (a.time || '').localeCompare(b.time || ''));

  const currentStatusObj = STATUS_OPTIONS.find(s => s.key === status) || STATUS_OPTIONS[0];
  const subWarning = subscriptionEnd ? Math.ceil((subscriptionEnd - new Date()) / 86400000) : null;

  if (loading) return (
    <View style={styles.loadingContainer}>
      <ActivityIndicator size="large" color="#16a34a" />
      <Text style={styles.loadingText}>Loading dashboard...</Text>
    </View>
  );

  return (
    <View style={{ flex: 1, backgroundColor: '#f8f9fa' }}>
      <ScrollView showsVerticalScrollIndicator={false}>

        {/* Top Bar */}
        <View style={styles.topBar}>
          <View>
            <Text style={styles.topBarTitle}>Dashboard</Text>
            <Text style={styles.topBarSub}>{today.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })}</Text>
          </View>
          <View style={styles.topBarRight}>
            {/* Nearby Doctors button */}
            <TouchableOpacity
              style={styles.nearbyBtn}
              onPress={() => navigation.navigate('PatientMap', { isDoctor: true })}
            >
              <Text style={styles.nearbyBtnText}>Nearby</Text>
            </TouchableOpacity>
            {!assistantActive && (
              <TouchableOpacity style={styles.menuBtn} onPress={() => setMenuVisible(true)}>
                <View style={styles.menuLine} />
                <View style={styles.menuLine} />
                <View style={styles.menuLine} />
              </TouchableOpacity>
            )}
            {assistantActive && (
              <View style={styles.assistantBadge}>
                <Text style={styles.assistantBadgeText}>Assistant</Text>
              </View>
            )}
          </View>
        </View>

        {/* Countdown Banner */}
        {subscriptionEnd && (
          <View style={[styles.subBanner, subWarning !== null && subWarning <= 3 && styles.subBannerRed]}>
            <Text style={styles.subBannerLabel}>{subWarning === 0 ? 'Subscription expired' : 'Free trial ends in'}</Text>
            {subWarning > 0 && <Text style={styles.subBannerCountdown}>{countdown}</Text>}
          </View>
        )}

        {/* Profile CV Card */}
        {!assistantActive && (
          <View style={styles.profileCard}>
            <View style={styles.coverContainer}>
              {profile?.photoMain
                ? <Image source={{ uri: profile.photoMain }} style={styles.coverPhoto} />
                : <View style={[styles.coverPhoto, { backgroundColor: '#dcfce7' }]} />
              }
              <View style={[styles.statusDotBadge, { backgroundColor: currentStatusObj.dot }]} />
            </View>
            <View style={styles.profileBody}>
              <View style={styles.profileHeader}>
                <View style={{ flex: 1 }}>
                  <Text style={styles.profileName}>Dr. {profile?.fullName}</Text>
                  {profile?.fullNameAr ? <Text style={styles.profileNameAr}>{profile.fullNameAr}</Text> : null}
                  <Text style={styles.profileSpecialty}>{profile?.specialty}</Text>
                </View>
                <View style={[styles.statusPill, { borderColor: currentStatusObj.color, backgroundColor: currentStatusObj.color + '12' }]}>
                  <Text style={[styles.statusPillText, { color: currentStatusObj.color }]}>{currentStatusObj.label}</Text>
                </View>
              </View>
              <View style={styles.divider} />
              <View style={styles.detailsGrid}>
                <View style={styles.detailItem}>
                  <Text style={styles.detailLabel}>CABINET</Text>
                  <Text style={styles.detailValue}>{profile?.cabinetName}</Text>
                  {profile?.cabinetNameAr ? <Text style={styles.detailValueAr}>{profile.cabinetNameAr}</Text> : null}
                </View>
                <View style={styles.detailItem}>
                  <Text style={styles.detailLabel}>PHONE</Text>
                  <Text style={styles.detailValue}>{profile?.phone}</Text>
                </View>
                <View style={styles.detailItem}>
                  <Text style={styles.detailLabel}>VISIT COST</Text>
                  <Text style={styles.detailValue}>{profile?.visitCost} DA</Text>
                </View>
                <View style={styles.detailItem}>
                  <Text style={styles.detailLabel}>MODE</Text>
                  <Text style={styles.detailValue}>{acceptMode === 'auto' ? 'Auto Accept' : 'Manual'}</Text>
                </View>
              </View>
              {profile?.equipment ? (
                <View style={styles.equipmentBox}>
                  <Text style={styles.detailLabel}>EQUIPMENT</Text>
                  <Text style={styles.equipmentText}>{profile.equipment}</Text>
                </View>
              ) : null}
              {(profile?.photoEntrance || profile?.photoStreet) && (
                <View style={styles.photoRow}>
                  {profile.photoEntrance && (
                    <View style={styles.photoThumbWrap}>
                      <Image source={{ uri: profile.photoEntrance }} style={styles.photoThumb} />
                      <Text style={styles.photoThumbLabel}>Entrance</Text>
                    </View>
                  )}
                  {profile.photoStreet && (
                    <View style={styles.photoThumbWrap}>
                      <Image source={{ uri: profile.photoStreet }} style={styles.photoThumb} />
                      <Text style={styles.photoThumbLabel}>Street</Text>
                    </View>
                  )}
                </View>
              )}
            </View>
          </View>
        )}

        {/* Status & Mode (hidden in assistant mode) */}
        {!assistantActive && (
          <>
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Current Status</Text>
              <Text style={styles.sectionSub}>Patients see this in real time</Text>
              <View style={styles.statusGrid}>
                {STATUS_OPTIONS.map(opt => (
                  <TouchableOpacity
                    key={opt.key}
                    style={[styles.statusBtn, status === opt.key && { borderColor: opt.color, backgroundColor: opt.color + '10' }]}
                    onPress={() => updateStatus(opt.key)}
                  >
                    <View style={[styles.statusBtnDot, { backgroundColor: opt.dot }]} />
                    <View>
                      <Text style={[styles.statusBtnLabel, status === opt.key && { color: opt.color, fontWeight: '700' }]}>{opt.label}</Text>
                      <Text style={styles.statusBtnLabelAr}>{opt.labelAr}</Text>
                    </View>
                  </TouchableOpacity>
                ))}
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Reservation Mode</Text>
              <View style={styles.modeRow}>
                <TouchableOpacity style={[styles.modeBtn, acceptMode === 'auto' && styles.modeBtnActive]} onPress={() => updateAcceptMode('auto')}>
                  <Text style={[styles.modeBtnText, acceptMode === 'auto' && styles.modeBtnTextActive]}>Auto Accept</Text>
                  <Text style={styles.modeBtnSub}>Confirmed instantly</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[styles.modeBtn, acceptMode === 'manual' && styles.modeBtnActive]} onPress={() => updateAcceptMode('manual')}>
                  <Text style={[styles.modeBtnText, acceptMode === 'manual' && styles.modeBtnTextActive]}>Manual Approve</Text>
                  <Text style={styles.modeBtnSub}>You confirm each one</Text>
                </TouchableOpacity>
              </View>
            </View>
          </>
        )}

        {/* Assistant Mode */}
        <View style={styles.section}>
          <View style={styles.sectionRow}>
            <View style={{ flex: 1 }}>
              <Text style={styles.sectionTitle}>Assistant Mode</Text>
              <Text style={styles.sectionSub}>{assistantActive ? 'Active — assistant controls today' : "Hand over today's queue with a PIN"}</Text>
            </View>
            <TouchableOpacity style={[styles.assistantBtn, assistantActive && styles.assistantBtnActive]} onPress={handleAssistantBtn}>
              <Text style={[styles.assistantBtnText, assistantActive && styles.assistantBtnTextActive]}>
                {assistantActive ? 'Deactivate' : 'Activate'}
              </Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Today's Queue */}
        <View style={styles.section}>
          <View style={styles.sectionRow}>
            <View>
              <Text style={styles.sectionTitle}>Today's Queue</Text>
              <Text style={styles.sectionSub}>{todayQueue.length} patients scheduled</Text>
            </View>
            {todayQueue.length > 0 && (
              <TouchableOpacity style={styles.exportBtn} onPress={exportPDF}>
                <Text style={styles.exportBtnText}>Export PDF</Text>
              </TouchableOpacity>
            )}
          </View>
          {todayQueue.length === 0 ? (
            <View style={styles.emptyBox}>
              <Text style={styles.emptyText}>No patients scheduled today</Text>
              {!assistantActive && <Text style={styles.emptySub}>Set status to "In Office" to receive bookings</Text>}
            </View>
          ) : (
            todayQueue.map((item, index) => {
              const sc = item.status === 'confirmed' ? '#16a34a' : '#d97706';
              return (
                <View key={item.id} style={styles.queueRow}>
                  <View style={styles.queueNum}><Text style={styles.queueNumText}>{index + 1}</Text></View>
                  <View style={styles.queueTime}><Text style={styles.queueTimeText}>{item.time || '--:--'}</Text></View>
                  <View style={styles.queueInfo}>
                    <Text style={styles.queueName}>{item.patientName || 'Patient'}</Text>
                    <Text style={styles.queuePhone}>{item.patientPhone || '—'}</Text>
                    {item.note ? <Text style={styles.queueNote}>{item.note}</Text> : null}
                  </View>
                  <View style={styles.queueActions}>
                    <View style={[styles.queueDot, { backgroundColor: sc }]} />
                    {item.status === 'pending' && (
                      <TouchableOpacity onPress={() => confirmRes(item.id)}>
                        <Text style={styles.queueConfirm}>Confirm</Text>
                      </TouchableOpacity>
                    )}
                    <TouchableOpacity onPress={() => handleCancel(item)}>
                      <Text style={styles.queueCancel}>Cancel</Text>
                    </TouchableOpacity>
                  </View>
                </View>
              );
            })
          )}
        </View>

        {/* Calendar Slot Manager (F) */}
        {!assistantActive && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Calendar & Slots</Text>
            <Text style={styles.sectionSub}>Tap a day to manage its capacity</Text>

            {/* Horizontal 14-day calendar strip */}
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              style={styles.calendarScroll}
              contentContainerStyle={styles.calendarContent}
            >
              {calendarDays.map(day => {
                const s = slots[day] || { max: profile?.maxSlots || 10, booked: 0 };
                const available = Math.max(0, s.max - s.booked);
                const fc = available === 0 ? '#dc2626' : available <= 3 ? '#d97706' : '#16a34a';
                const isSelected = (selectedCalendarDay || todayKey) === day;
                const d = new Date(day);
                const dayName = day === todayKey ? 'Today'
                  : day === calendarDays[1] ? 'Tomorrow'
                  : d.toLocaleDateString('en-GB', { weekday: 'short' });
                const dayNum = d.getDate();
                return (
                  <TouchableOpacity
                    key={day}
                    style={[styles.calendarChip, isSelected && styles.calendarChipSelected]}
                    onPress={() => { setSelectedCalendarDay(day); setEditingSlotDate(null); }}
                  >
                    <Text style={[styles.calendarChipDay, isSelected && styles.calendarChipTextSelected]}>{dayName}</Text>
                    <Text style={[styles.calendarChipNum, isSelected && styles.calendarChipTextSelected]}>{dayNum}</Text>
                    <Text style={[styles.calendarChipSlots, { color: isSelected ? 'rgba(255,255,255,0.9)' : fc }]}>
                      {available}/{s.max}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </ScrollView>

            {/* Slot management for selected day */}
            {(() => {
              const day = selectedCalendarDay || todayKey;
              const s = slots[day] || { max: profile?.maxSlots || 10, booked: 0 };
              const available = Math.max(0, s.max - s.booked);
              const fc = available === 0 ? '#dc2626' : available <= 3 ? '#d97706' : '#16a34a';
              const isEditing = editingSlotDate === day;
              const d = new Date(day);
              const label = day === todayKey ? 'Today'
                : d.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' });
              return (
                <View style={styles.slotCard}>
                  <View style={styles.slotTop}>
                    <Text style={styles.slotDayLabel}>{label}</Text>
                    <Text>
                      <Text style={{ color: fc, fontWeight: '700' }}>{available}</Text>
                      <Text style={styles.slotAvailSub}> / {s.max} slots</Text>
                    </Text>
                  </View>
                  <View style={styles.progressBg}>
                    <View style={[styles.progressFill, { width: `${Math.min(100, (s.booked / s.max) * 100)}%`, backgroundColor: fc }]} />
                  </View>
                  {isEditing ? (
                    <View style={styles.slotEditRow}>
                      <TextInput
                        style={styles.slotInput}
                        value={newSlotValue}
                        onChangeText={setNewSlotValue}
                        keyboardType="numeric"
                        placeholder={`Current: ${s.max}`}
                        maxLength={3}
                        autoFocus
                      />
                      <TouchableOpacity style={styles.slotSaveBtn} onPress={() => saveSlot(day, newSlotValue)}>
                        <Text style={styles.slotSaveBtnText}>Save</Text>
                      </TouchableOpacity>
                      <TouchableOpacity style={styles.slotBackBtn} onPress={() => setEditingSlotDate(null)}>
                        <Text style={styles.slotBackBtnText}>Back</Text>
                      </TouchableOpacity>
                    </View>
                  ) : (
                    <TouchableOpacity style={styles.slotEditBtn} onPress={() => { setNewSlotValue(s.max.toString()); setEditingSlotDate(day); }}>
                      <Text style={styles.slotEditBtnText}>Change slots</Text>
                    </TouchableOpacity>
                  )}
                </View>
              );
            })()}
          </View>
        )}

        {/* All Reservations */}
        {!assistantActive && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>All Reservations ({reservations.length})</Text>
            {reservations.length === 0 ? (
              <View style={styles.emptyBox}><Text style={styles.emptyText}>No reservations yet</Text></View>
            ) : (
              reservations.map(item => {
                const dateStr = item.date?.toDate ? item.date.toDate().toLocaleDateString('en-GB') : item.date;
                const sc = item.status === 'confirmed' ? '#16a34a' : item.status === 'cancelled' ? '#dc2626' : '#d97706';
                return (
                  <View key={item.id} style={styles.resCard}>
                    <View style={styles.resCardTop}>
                      <Text style={styles.resCardName}>{item.patientName || 'Patient'}</Text>
                      <View style={[styles.resCardBadge, { backgroundColor: sc + '18', borderColor: sc }]}>
                        <Text style={[styles.resCardBadgeText, { color: sc }]}>{item.status || 'pending'}</Text>
                      </View>
                    </View>
                    <Text style={styles.resCardDate}>{dateStr}{item.time ? ` · ${item.time}` : ''}</Text>
                    {item.note ? <Text style={styles.resCardNote}>{item.note}</Text> : null}
                    {item.status === 'pending' && (
                      <View style={styles.resCardActions}>
                        <TouchableOpacity style={styles.resConfirmBtn} onPress={() => confirmRes(item.id)}>
                          <Text style={styles.resConfirmText}>Confirm</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.resCancelBtnStyle} onPress={() => handleCancel(item)}>
                          <Text style={styles.resCancelText}>Cancel</Text>
                        </TouchableOpacity>
                      </View>
                    )}
                    {item.status === 'confirmed' && (
                      <TouchableOpacity style={[styles.resCancelBtnStyle, { marginTop: 8 }]} onPress={() => handleCancel(item)}>
                        <Text style={styles.resCancelText}>Cancel booking</Text>
                      </TouchableOpacity>
                    )}
                  </View>
                );
              })
            )}
          </View>
        )}

        <View style={{ height: 80 }} />
      </ScrollView>

      {/* Settings Menu */}
      <Modal visible={menuVisible} transparent animationType="fade" onRequestClose={() => setMenuVisible(false)}>
        <TouchableOpacity style={styles.menuOverlay} activeOpacity={1} onPress={() => setMenuVisible(false)}>
          <View style={styles.menuSheet}>
            <Text style={styles.menuTitle}>Settings</Text>
            <TouchableOpacity style={styles.menuItem} onPress={() => { setMenuVisible(false); navigation.navigate('EditProfile', { isNewDoctor: false }); }}>
              <Text style={styles.menuItemText}>Edit Profile</Text>
              <Text style={styles.menuItemSub}>Update clinic info, photos, specialty</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.menuItem} onPress={() => { setMenuVisible(false); setPinMode(savedPin ? 'enter' : 'set'); setPinInput(''); setPinModalVisible(true); }}>
              <Text style={styles.menuItemText}>Assistant PIN</Text>
              <Text style={styles.menuItemSub}>{savedPin ? 'Change existing PIN' : 'Set up assistant PIN'}</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.menuItem} onPress={() => { setMenuVisible(false); setPwModalVisible(true); }}>
              <Text style={styles.menuItemText}>Change Password</Text>
              <Text style={styles.menuItemSub}>Update your account password</Text>
            </TouchableOpacity>
      <TouchableOpacity 
        style={[styles.menuItem, { borderBottomWidth: 0 }]} 
        onPress={async () => {
          try {
            Alert.alert(
              "Sign Out",
              "Are you sure you want to sign out?",
              [
                {
                  text: "Cancel",
                  onPress: () => {},
                  style: "cancel"
                },
                {
                  text: "Sign Out",
                  onPress: async () => {
                    setMenuVisible(false);
                    await auth.signOut();
                    navigation.reset({
                      index: 0,
                      routes: [{ name: 'Login' }],
                    });
                  },
                  style: "destructive"
                }
              ]
            );
          } catch (error) {
            Alert.alert("Error", "Could not sign out: " + error.message);
          }
        }}
      >
        <Text style={[styles.menuItemText, { color: '#dc2626' }]}>🚪 Sign Out</Text>
      </TouchableOpacity>
    </View>
  </TouchableOpacity>
</Modal>

      {/* PIN Modal */}
      <Modal visible={pinModalVisible} transparent animationType="slide" onRequestClose={() => setPinModalVisible(false)}>
        <View style={styles.modalOverlay}>
          <View style={styles.modalSheet}>
            <Text style={styles.modalTitle}>{pinMode === 'set' ? 'Set Assistant PIN' : 'Enter Assistant PIN'}</Text>
            <Text style={styles.modalSub}>{pinMode === 'set' ? 'Create a PIN for your assistant' : 'Enter PIN to activate assistant mode'}</Text>
            <TextInput style={styles.modalInput} value={pinInput} onChangeText={setPinInput} keyboardType="numeric" secureTextEntry maxLength={8} placeholder="Enter PIN" autoFocus />
            <TouchableOpacity style={styles.modalBtn} onPress={handlePinSubmit}>
              <Text style={styles.modalBtnText}>{pinMode === 'set' ? 'Set PIN' : 'Unlock'}</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.modalCancelBtn} onPress={() => setPinModalVisible(false)}>
              <Text style={styles.modalCancelText}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>

      {/* Password Modal */}
      <Modal visible={pwModalVisible} transparent animationType="slide" onRequestClose={() => setPwModalVisible(false)}>
        <View style={styles.modalOverlay}>
          <View style={styles.modalSheet}>
            <Text style={styles.modalTitle}>Change Password</Text>
            <TextInput style={styles.modalInput} value={currentPw} onChangeText={setCurrentPw} secureTextEntry placeholder="Current password" />
            <TextInput style={styles.modalInput} value={newPw} onChangeText={setNewPw} secureTextEntry placeholder="New password" />
            <TextInput style={styles.modalInput} value={confirmPw} onChangeText={setConfirmPw} secureTextEntry placeholder="Confirm new password" />
            <TouchableOpacity style={styles.modalBtn} onPress={handlePasswordChange}>
              <Text style={styles.modalBtnText}>Update Password</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.modalCancelBtn} onPress={() => setPwModalVisible(false)}>
              <Text style={styles.modalCancelText}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f8f9fa' },
  loadingText: { marginTop: 12, color: '#6b7280', fontSize: 14 },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 56, paddingBottom: 16 },
  topBarTitle: { fontSize: 28, fontWeight: '800', color: '#111827', letterSpacing: -0.5 },
  topBarSub: { fontSize: 13, color: '#6b7280', marginTop: 2 },
  topBarRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  nearbyBtn: { backgroundColor: '#f0fdf4', borderWidth: 1.5, borderColor: '#16a34a', borderRadius: 20, paddingVertical: 7, paddingHorizontal: 14 },
  nearbyBtnText: { color: '#16a34a', fontSize: 13, fontWeight: '700' },
  menuBtn: { padding: 8, alignItems: 'flex-end', justifyContent: 'center' },
  menuLine: { width: 22, height: 2, backgroundColor: '#374151', borderRadius: 2, marginVertical: 2 },
  assistantBadge: { backgroundColor: '#eff6ff', borderWidth: 1, borderColor: '#2563eb', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6 },
  assistantBadgeText: { color: '#2563eb', fontSize: 12, fontWeight: '600' },
  subBanner: { marginHorizontal: 20, marginBottom: 12, backgroundColor: '#f0fdf4', borderRadius: 12, paddingVertical: 12, paddingHorizontal: 16, borderWidth: 1, borderColor: '#bbf7d0' },
  subBannerRed: { backgroundColor: '#fee2e2', borderColor: '#fecaca' },
  subBannerLabel: { fontSize: 12, color: '#6b7280', textAlign: 'center', marginBottom: 4 },
  subBannerCountdown: { fontSize: 20, fontWeight: '800', color: '#16a34a', textAlign: 'center', letterSpacing: 0.5 },
  profileCard: { marginHorizontal: 20, marginBottom: 16, backgroundColor: '#fff', borderRadius: 20, overflow: 'hidden', elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 12 },
  coverContainer: { position: 'relative' },
  coverPhoto: { width: '100%', height: 140 },
  statusDotBadge: { position: 'absolute', bottom: 12, right: 12, width: 14, height: 14, borderRadius: 7, borderWidth: 2.5, borderColor: '#fff' },
  profileBody: { padding: 20 },
  profileHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  profileName: { fontSize: 20, fontWeight: '800', color: '#111827' },
  profileNameAr: { fontSize: 15, color: '#374151', marginTop: 2, textAlign: 'right', fontWeight: '600' },
  profileSpecialty: { fontSize: 14, color: '#6b7280', marginTop: 3 },
  statusPill: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 5 },
  statusPillText: { fontSize: 12, fontWeight: '600' },
  divider: { height: 1, backgroundColor: '#f3f4f6', marginVertical: 16 },
  detailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  detailItem: { width: '45%' },
  detailLabel: { fontSize: 10, color: '#9ca3af', fontWeight: '700', letterSpacing: 0.8, marginBottom: 3 },
  detailValue: { fontSize: 14, color: '#111827', fontWeight: '600' },
  detailValueAr: { fontSize: 13, color: '#374151', textAlign: 'right', marginTop: 2 },
  equipmentBox: { marginTop: 16, padding: 12, backgroundColor: '#f9fafb', borderRadius: 10, borderWidth: 1, borderColor: '#f3f4f6' },
  equipmentText: { fontSize: 13, color: '#374151', marginTop: 4, lineHeight: 20 },
  photoRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
  photoThumbWrap: { flex: 1 },
  photoThumb: { width: '100%', height: 80, borderRadius: 10 },
  photoThumbLabel: { fontSize: 11, color: '#9ca3af', textAlign: 'center', marginTop: 4 },
  section: { marginHorizontal: 20, marginBottom: 14, backgroundColor: '#fff', borderRadius: 20, padding: 20, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 8 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 2 },
  sectionSub: { fontSize: 12, color: '#9ca3af', marginBottom: 14 },
  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statusBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1.5, borderColor: '#e5e7eb', borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12 },
  statusBtnDot: { width: 8, height: 8, borderRadius: 4 },
  statusBtnLabel: { fontSize: 13, color: '#374151', fontWeight: '500' },
  statusBtnLabelAr: { fontSize: 11, color: '#9ca3af' },
  modeRow: { flexDirection: 'row', gap: 10 },
  modeBtn: { flex: 1, borderWidth: 1.5, borderColor: '#e5e7eb', borderRadius: 12, padding: 14 },
  modeBtnActive: { borderColor: '#16a34a', backgroundColor: '#f0fdf4' },
  modeBtnText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },
  modeBtnTextActive: { color: '#16a34a' },
  modeBtnSub: { fontSize: 11, color: '#9ca3af', marginTop: 3 },
  assistantBtn: { borderWidth: 1.5, borderColor: '#e5e7eb', borderRadius: 12, paddingVertical: 9, paddingHorizontal: 16 },
  assistantBtnActive: { borderColor: '#2563eb', backgroundColor: '#eff6ff' },
  assistantBtnText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },
  assistantBtnTextActive: { color: '#2563eb' },
  exportBtn: { backgroundColor: '#16a34a', paddingVertical: 7, paddingHorizontal: 14, borderRadius: 10 },
  exportBtnText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  emptyBox: { paddingVertical: 24, alignItems: 'center' },
  emptyText: { fontSize: 15, color: '#9ca3af', fontWeight: '500' },
  emptySub: { fontSize: 12, color: '#d1d5db', marginTop: 4, textAlign: 'center' },
  queueRow: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f3f4f6', gap: 10 },
  queueNum: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#f0fdf4', alignItems: 'center', justifyContent: 'center' },
  queueNumText: { fontSize: 13, fontWeight: '700', color: '#16a34a' },
  queueTime: { width: 48, paddingTop: 4 },
  queueTimeText: { fontSize: 13, fontWeight: '600', color: '#374151' },
  queueInfo: { flex: 1 },
  queueName: { fontSize: 15, fontWeight: '700', color: '#111827' },
  queuePhone: { fontSize: 13, color: '#6b7280', marginTop: 2 },
  queueNote: { fontSize: 12, color: '#9ca3af', marginTop: 3, fontStyle: 'italic' },
  queueActions: { alignItems: 'flex-end', gap: 6 },
  queueDot: { width: 8, height: 8, borderRadius: 4 },
  queueConfirm: { fontSize: 12, fontWeight: '600', color: '#16a34a' },
  queueCancel: { fontSize: 12, fontWeight: '600', color: '#dc2626' },
  slotCard: { borderWidth: 1, borderColor: '#f3f4f6', borderRadius: 12, padding: 14, marginBottom: 10 },
  slotTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  slotDayLabel: { fontSize: 14, fontWeight: '700', color: '#111827' },
  slotAvailSub: { color: '#9ca3af' },
  progressBg: { height: 4, backgroundColor: '#f3f4f6', borderRadius: 2, marginBottom: 10 },
  progressFill: { height: 4, borderRadius: 2 },
  slotEditBtn: { alignSelf: 'flex-start', backgroundColor: '#f3f4f6', paddingVertical: 5, paddingHorizontal: 12, borderRadius: 8 },
  slotEditBtnText: { fontSize: 12, color: '#374151', fontWeight: '500' },
  slotEditRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  slotInput: { flex: 1, borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 8, padding: 8, fontSize: 15 },
  slotSaveBtn: { backgroundColor: '#16a34a', paddingVertical: 8, paddingHorizontal: 14, borderRadius: 8 },
  slotSaveBtnText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  slotBackBtn: { backgroundColor: '#f3f4f6', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8 },
  slotBackBtnText: { color: '#374151', fontSize: 13 },

  // Calendar strip (F)
  calendarScroll: { marginBottom: 14 },
  calendarContent: { paddingVertical: 4, gap: 8 },
  calendarChip: { width: 62, borderRadius: 14, borderWidth: 1.5, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 4 },
  calendarChipSelected: { backgroundColor: '#16a34a', borderColor: '#16a34a' },
  calendarChipDay: { fontSize: 10, fontWeight: '600', color: '#9ca3af', marginBottom: 3 },
  calendarChipNum: { fontSize: 18, fontWeight: '800', color: '#111827' },
  calendarChipSlots: { fontSize: 10, fontWeight: '600', marginTop: 3 },
  calendarChipTextSelected: { color: '#fff' },
  resCard: { borderWidth: 1, borderColor: '#f3f4f6', borderRadius: 12, padding: 14, marginBottom: 10 },
  resCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  resCardName: { fontSize: 15, fontWeight: '700', color: '#111827' },
  resCardBadge: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3 },
  resCardBadgeText: { fontSize: 11, fontWeight: '600' },
  resCardDate: { fontSize: 13, color: '#6b7280' },
  resCardNote: { fontSize: 12, color: '#9ca3af', marginTop: 4, fontStyle: 'italic' },
  resCardActions: { flexDirection: 'row', gap: 8, marginTop: 10 },
  resConfirmBtn: { flex: 1, backgroundColor: '#f0fdf4', borderWidth: 1, borderColor: '#16a34a', borderRadius: 8, padding: 9, alignItems: 'center' },
  resConfirmText: { color: '#16a34a', fontWeight: '600', fontSize: 13 },
  resCancelBtnStyle: { flex: 1, backgroundColor: '#fef2f2', borderWidth: 1, borderColor: '#dc2626', borderRadius: 8, padding: 9, alignItems: 'center' },
  resCancelText: { color: '#dc2626', fontWeight: '600', fontSize: 13 },
  menuOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  menuSheet: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: 44 },
  menuTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 20 },
  menuItem: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  menuItemText: { fontSize: 16, fontWeight: '600', color: '#111827' },
  menuItemSub: { fontSize: 12, color: '#9ca3af', marginTop: 3 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 28, paddingBottom: 44 },
  modalTitle: { fontSize: 20, fontWeight: '800', color: '#111827', marginBottom: 6 },
  modalSub: { fontSize: 13, color: '#6b7280', marginBottom: 20 },
  modalInput: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 12, padding: 14, fontSize: 16, marginBottom: 12, backgroundColor: '#fafafa' },
  modalBtn: { backgroundColor: '#16a34a', padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 4 },
  modalBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  modalCancelBtn: { padding: 14, alignItems: 'center', marginTop: 4 },
  modalCancelText: { color: '#6b7280', fontSize: 15 },
});